config/routes.rb
Artspace::Application.routes.draw do

  root "welcome#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "signup", to: "users#new"
  get "users/:id/manage", to: "users#manage", as: "manage"

  resources :users, except: [:new, :index]

  resources :spaces do
    resources :availabilities, only: [:new, :update]
  end

  get "spaces/:space_id/edit_availabilities", to: "availabilities#edit", as: "edit_availabilities"
  post "spaces/availabilities/update", to: "availabilities#update", as: "update_availabilities"
  resources :availabilities, only: [:create]
  resources :reservations, only: [:create, :destroy]
  get "reservations/confirmation", to: "reservations#confirmation", as: "reservations_confirmation"

  get  "spaces/:id/pic", to: "spaces#edit_pic", as: "edit_pic"
  
  post "delete_pic", to: "spaces#delete_photo"
  post "update_pic", to: "spaces#update_pic", as: "update_pic"
  resources :payments, only: [:new]
  get "payments/callback", to: "payments#callback", as: "payments_callback"
  post "payments/charge", to: "payments#charge", as: "payment_charge"
  get "payments/pos", to: "payments#pos", as: "pos"

  get "spaces/:space_id/reservations", to: "reservations#index", as: "view_reservations"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :admins, foreign_key: :administrator_id
  has_many :spaces_administrated, through: :admins, source: :space

  has_many :spaces_created, class_name: "Space", foreign_key: "creator_id"

  has_many :reservations, foreign_key: :renter_id
  has_many :rentals, through: :reservations, source: :space

  has_many :payments, foreign_key: :creator_id

  has_secure_password
  validates_presence_of :password, :on => :create

  def upcoming_reservations
  	reservations.where("start_time > ?", Date.today).order(:start_time)
  end

  def favorite_spaces
    reservation_count = reservations.group_by(&:space_id).map{ |space, res| {space => res.count} }
    top3 = reservation_count.map{ |r| p r.flatten}.sort{|a,b| b[1]<=>a[1] }.take(3)
    top3.map{ |t| Space.find(t[0])}
  end

  def publishable_key
    self.payments.first.publishable_api_key
  end

  def secret_key
    self.payments.first.secret_api_key
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if current_user
      redirect_to user_path(current_user)
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "Invalid info - check to make sure passwords match"
      render 'users/new'
    end
  end

  def show
  end

  def manage
    if session[:current_user_id]
      @spaces = current_user.spaces_created
      creator_id = @spaces.first.creator_id
    else
      render "welcome/index"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/manage.html.erb
<%= render "shared/top_nav" %>
<div id="page">
  <div id="title7">CLICK ON A TITLE TO VIEW YOUR SPACE</div>
  <div id="nav_wrapper">
    <ul id="manager_nav">
      <% @spaces.each do |space| %>
      <li>
        <% space_name = space.title.gsub(/\s/, "") %>
        <%= link_to "#{space.title}", "##{space_name}" %>
      </li>
      <% end %>
    </ul>
  </div>


  <% @spaces.each do |space| %>

      <% space_name = space.title.gsub(/\s/, "") %>
      <h2 id="link"><span id="<%=space_name%>"></span><%= link_to "#{space.title}", space_path(space.id) %></h2>


      <div class="upcoming_reservations">
        <h2 class="inactive"><% if space.active == 0 %>INACTIVE<% end %></h2>
        <h3> UPCOMING RESERVATIONS </h3>
        <% if space.upcoming_reservations == [] %>
          <p><span class="color">There are no upcoming reservations for this space.</span></p>
        <% end %>
        <% space.upcoming_reservations.order(:start_time).limit(5).each do |r| %>
          <p><span class="color">RENTER </span><%= r.renter.first_name %>  <%= r.renter.last_name %><span class="color"> FROM </span><%= r.start_time.in_time_zone(-6).strftime("%a %m/%d/%y      %I:%M %p") %><span class="color"> TO </span><%= r.end_time.in_time_zone(-6).strftime("%I:%M %p") %></p>
        <% end %>
      </div>
      <div class="options">
        <% if space.active == 1 %>
          <p><%= link_to "EDIT DETAILS", edit_space_path(space.id)%></p>
        <% else %>
          <p><%= link_to "ACTIVATE/EDIT DETAILS", edit_space_path(space.id)%></p>
        <% end %>
        <p><%= link_to "EDIT SCHEDULE", edit_availabilities_path(space.id)%></p>
        <p><%= link_to "EDIT PHOTOS", edit_pic_path(space.id) %></p>
        <p><%= link_to "VIEW ALL UPCOMING RESERVATIONS", view_reservations_path(space.id) %></p>
        <% if space.active == 1 %>
        <%= button_to "Deactivate Space", { action: "destroy", id: space.id, :controller=>"spaces" },
                      class: "main_button gray_button", method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>

  <% end %>

</div>
<%= render "shared/footer" %>

app/views/users/new.html.erb
<%= render "shared/top_nav" %>
<%= render "shared/user_form" %>
<% flash.each do |key, val| %>
  <%= val %>
<% end %>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<div id="page">
	<%= render "shared/top_nav" %>



	<div id="favorite_label"><h2>Favorite Spaces</h2></div>	
		<div id="favorite" class="user_show">

		  <% current_user.favorite_spaces.each do |fave| %>
		  <div class="fave"><p><%= link_to "#{fave.title}", space_path(fave.id) %></p></div>
		  <% end %>
		</div>

	<div id="upcoming" class="user_show">
	  <h2>Upcoming Rentals</h2>
	  <% current_user.upcoming_reservations.each do |r| %>
	  <p><span class="color">AT</span><%= r.space.title %><span class="color">FROM</span><%= r.start_time.in_time_zone(-6).strftime("%a %m/%d/%y     %I:%M %p") %><span class="color">TO</span><%= r.end_time.in_time_zone(-6).strftime("%I:%M %p") %></p>
	  <%= r.space.address %>     <%= r.space.city %>,    <%= r.space.state %>     <%= r.space.zipcode %>
	  <hr>
	  <% end %>
	</div>
<%= render "shared/footer" %>
</div>