config/routes.rb
Artspace::Application.routes.draw do

  root "welcome#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "signup", to: "users#new"
  get "users/:id/manage", to: "users#manage", as: "manage"

  resources :users, except: [:new, :index]

  resources :spaces do
    resources :availabilities, only: [:new, :update]
  end

  get "spaces/:space_id/edit_availabilities", to: "availabilities#edit", as: "edit_availabilities"
  post "spaces/availabilities/update", to: "availabilities#update", as: "update_availabilities"
  resources :availabilities, only: [:create]
  resources :reservations, only: [:create, :destroy]
  get "reservations/confirmation", to: "reservations#confirmation", as: "reservations_confirmation"

  get  "spaces/:id/pic", to: "spaces#edit_pic", as: "edit_pic"
  
  post "delete_pic", to: "spaces#delete_photo"
  post "update_pic", to: "spaces#update_pic", as: "update_pic"
  resources :payments, only: [:new]
  get "payments/callback", to: "payments#callback", as: "payments_callback"
  post "payments/charge", to: "payments#charge", as: "payment_charge"
  get "payments/pos", to: "payments#pos", as: "pos"

  get "spaces/:space_id/reservations", to: "reservations#index", as: "view_reservations"

end

app/views/shared/_availability_calendar.html.erb
<div id="calendarbox">
  <button class="main_button red_button" id="create_availabilities" data-space-id='<%=params[:space_id]%>'>Create availabilities</button>
  <div id="calendar">
  </div>
</div>

<script>
$(document).ready(function() {
  show_creation_calendar("#calendar");
});
</script>

app/views/shared/_calendar.html.erb
<script id='calendar_info' type='application/json'>
 <%= @calendar_info.html_safe %>
</script>
<% if current_user %>
<script>
$(document).ready(function() {
  handler = StripeCheckout.configure(stripe_config());
});
</script>
<% end %>

<div id="calendarbox">
  <% if current_user %>
  <button class="main_button red_button" id="make_reservation" data-space-id='<%=@space.id%>' data-space-title='<%=@space.title%>' data-space-email='<%=@space.email%>' data-space-rate='<%=@space.rate%>'>Make Reservation</button>
  <% end %>
  <div id="calendar">
  </div>
  <div id="event_info" style="display: none;">
    <form id="event_form">
     <p><textarea name="description" id="description" cols="20" rows="5" placeholder="Please describe your intended use of the space as well as any equipment you may be bringing in."></textarea></p>
     <p> Number of people: <input type="text" name="count" id="count" /></p>
   </form>
  </div>
</div>

<script>

$(document).ready(function() {
  <% if current_user %>
    show_renter_calendar("#calendar");
  <% else %>
    show_renter_calendar("#calendar", read_only = true);
  <% end %>
});

</script>

app/views/shared/_edit_availability_calendar.html.erb
<script id='calendar_info' type='application/json'>
 <%= @calendar_info.html_safe %>
</script>
<div id="calendarbox">
  <button class="main_button red_button" id="edit_availabilities" data-space-id='<%=params[:space_id]%>' data-user-id='<%=@user_id%>'>Save availabilities</button>
  <div id="calendar">
  </div>
</div>

<script>
$(document).ready(function() {
  show_edit_availability_calendar("#calendar");
});
</script>

app/views/shared/_footer.html.erb
<div class="footer">&copy; 2014 ArtSpace</div>

app/views/shared/_pic_form.html.erb
  <p><%= s3_uploader_form callback_method: "POST", max_file_size: 1.megabytes, callback_param: "upload[image_url]", id: "s3-uploader" do %>
  <%= hidden_field_tag  "Content-Type", "" %>
  <%= file_field_tag :file, accept: "image/png,image/jpeg", multiple: true %></p>
  <% end %>

  <div id="uploads_container"></div>
  <div id="progress_container"></div>

<script id="template-upload" type="text/x-tmpl">
  <div id="file-{%=o.unique_id%}" class="upload" style="margin-right: auto; margin-left: auto;">
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>

app/views/shared/_search.html.erb
  <%= form_tag(spaces_path, :method => "get") do %>

	  <%= text_field_tag :title, params[:title], placeholder: "search for space", size: 20, id:"search_form2" %>
	  <%= text_field_tag :rate, params[:rate], placeholder: "max $", size: 10, id:"rate_form2" %>
	  <%= submit_tag "Search", :name => nil, :class => "main_button red_button" %>

  <% end %>

app/views/shared/_space_details.html.erb
<ul id="edit_space_fields">
  <li><p>please provide a title for your space<br>this is how artists will search for your space<br><%= f.text_field   :title, placeholder: "Title", :required => true  %></p></li>
  <li><p><%= f.text_area    :description, placeholder: "Description", size: "60x12", :required => true  %></p></li>
  <li><p><%= f.text_field   :dimensions, placeholder: "Dimensions", :required => true  %></p></li>

  <li><p>list any equipment that is provided in the space<br><%= f.text_area   :ammenities, placeholder: "Amenities", size: "60x6", :required => true  %></p></li>
  <p>Permitted Uses:</p>
  <p>
    <% for use in Use.find(:all) %>
      <div id="uses">
        <%= check_box_tag "space[use_ids][]", use.id, @space.uses.include?(use) %>
        <%= use.category %>
      </div>
    <% end %>
  </p>

  <li><p>please specify an hourly rental rate<br><%= f.number_field :rate, placeholder: "Rate", :required => true  %></p></li>
  <li><p>street address<br><%= f.text_field   :address, placeholder: "Address", :required => true  %></p></li>
  <li><p><%= f.text_field   :city, placeholder: "City", :required => true  %></p></li>
  <li><p><%= f.text_field   :state, placeholder: "State", :required => true  %></p></li>
  <li><p><%= f.text_field :zipcode, placeholder: "Zipcode", :required => true  %></p></li>
  <li><p>I would like to receive emails regarding rentals here<br><%= f.email_field  :email, placeholder: "Email", :required => true  %></p></li>
  <li><p>business phonenumber<br><%= f.text_field :phone, placeholder: "Phone" %></p></li>
</ul>

app/views/shared/_space_form.html.erb
<ul id="space_form_list">
  <%= form_for @space, :html => {:class => "spaceform"} do |f| %>
  <div id="form_container"></div>
  <li><p>please provide a title for your space<br>this is how artists will search for your space<br><%= f.text_field   :title, placeholder: "Title", :required => true %></p></li>
  <li><p><%= f.text_area    :description, placeholder: "Please provide a description of your space. Include anything you may want to share with artists who will be renting your space.", size: "60x12", :required => true %></p></li>
  <li><p><%= f.text_field   :dimensions, placeholder: "Dimensions", :required => true %></p></li>

  <li><p>Amenities<br><%= f.text_area   :ammenities, placeholder: "Please list any equipment that is provided in the space.", size: "60x6", :required => true %></p></li>
  <p>Permitted Uses:</p>
  <p>
    <% for use in Use.find(:all) %>
      <div id="uses">
        <%= check_box_tag "space[use_ids][]", use.id, @space.uses.include?(use) %>
        <%= use.category %>
      </div>
    <% end %>
  </p>

  <li><p>please specify an hourly rental rate<br><%= f.number_field :rate, placeholder: "Rate", :required => true %></p></li>
  <li><p>street address<br><%= f.text_field   :address, placeholder: "Address", :required => true %></p></li>
  <li><p><%= f.text_field   :city, placeholder: "City", :required => true %></p></li>
  <li><p><%= f.text_field   :state, placeholder: "State", :required => true %></p></li>
  <li><p><%= f.text_field :zipcode, placeholder: "Zipcode", :required => true %></p></li>
  <li><p>I would like to receive emails regarding rentals here<br><%= f.email_field  :email, placeholder: "Email", :required => true %></p></li>
  <li><p>business phonenumber<br><%= f.text_field :phone, placeholder: "Phone" %></p></li>
  <li><%= f.submit "Add Available times", class: "main_button gray_button pic_validate"%></li>
  <% end %>
</ul>

app/views/shared/_top_nav.html.erb
<div class="nav">
  <div class="hello"><%= "Hello, " + current_user.first_name + "!" if current_user%></div>
  <div class="search_bar"><%= render "shared/search" %></div>
  <%= image_tag "artspace.svg", id:"logo" %>
  <h1 id="title2">Space</h1>
  <% if current_user %>
  <%= link_to 'Home', root_url %>
  <%= link_to 'Profile', current_user %>
    <% if current_user.spaces_administrated == [] && current_user.spaces_created == [] %>
     <% else %>
     <%= link_to 'Manage', manage_path(current_user), method: :get %>
    <% end %>
  <%= link_to 'New Space', new_space_path %>
  <%= link_to 'Logout', logout_path, method: :delete %>
  <% else %>
  <%= link_to 'Login', login_path, method: :get %>
  <%= link_to 'Sign Up', signup_path, method: :get %>
  <% end %>
</div>

app/views/shared/_user_form.html.erb
<%= form_for @user, :html => {:class => "form"} do |f| %>
<p><%= f.text_field :first_name, placeholder: "First Name", :required => true %></p>
<p><%= f.text_field :last_name, placeholder: "Last Name", :required => true %></p>
<p><%= f.text_field :phone, placeholder: "Phone Number" %></p>
<p><%= f.email_field :email, placeholder: "Email", :required => true %></p>
<p><%= f.text_field :password, type: "password", placeholder: "Password", :required => true %></p>
<p><%= f.text_field :password_confirmation, type: "password", placeholder: "Confirm Password", :required => true %></p>
<%= f.submit "Sign Up", class: "main_button gray_button" %>
<% end %>