config/routes.rb
Artspace::Application.routes.draw do

  root "welcome#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "signup", to: "users#new"
  get "users/:id/manage", to: "users#manage", as: "manage"

  resources :users, except: [:new, :index]

  resources :spaces do
    resources :availabilities, only: [:new, :update]
  end

  get "spaces/:space_id/edit_availabilities", to: "availabilities#edit", as: "edit_availabilities"
  post "spaces/availabilities/update", to: "availabilities#update", as: "update_availabilities"
  resources :availabilities, only: [:create]
  resources :reservations, only: [:create, :destroy]
  get "reservations/confirmation", to: "reservations#confirmation", as: "reservations_confirmation"

  get  "spaces/:id/pic", to: "spaces#edit_pic", as: "edit_pic"
  
  post "delete_pic", to: "spaces#delete_photo"
  post "update_pic", to: "spaces#update_pic", as: "update_pic"
  resources :payments, only: [:new]
  get "payments/callback", to: "payments#callback", as: "payments_callback"
  post "payments/charge", to: "payments#charge", as: "payment_charge"
  get "payments/pos", to: "payments#pos", as: "pos"

  get "spaces/:space_id/reservations", to: "reservations#index", as: "view_reservations"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @upload = Photo.new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="bar_style bar1">
</div>
<div class="bar_style bar2">
</div>
<div class="bar_style bar3">
</div>
<%= image_tag "artspace.svg", id:"logo", class: "homelogo" %>
<h1 id="title">Artspace</h1>
<div id="search">
  <%= form_tag(spaces_path, :method => "get") do %>
	<p>
	  <%= text_field_tag :title, params[:title], placeholder: "find space for your artistic endeavors", size: 20, class:"search_style", id:"search_size" %>
	  <%= text_field_tag :rate, params[:rate], placeholder: "max $", size: 10, class:"search_style", id:"rate_size" %>
	  <%= submit_tag "Search", :name => nil, :class => "main_button red_button" %>
	</p>
  <% end %>
</div>
<% if session[:current_user_id] %>
	<div class="home_options top_home_link">
	  <p>|<%= link_to 'Profile', user_path(session[:current_user_id]) %></p>
	</div>
	<div class="home_options bottom_home_link">  
	  <p>|<%= link_to 'Logout', logout_path, method: :delete %></p>
	</div>
<% else %>
	<div class="home_options top_home_link">
	  <p>|<%= link_to 'Login', login_path, method: :get %></p>
	</div>
	<div class="home_options bottom_home_link">  
	  <p>|<%= link_to 'Sign Up', signup_path, method: :get %></p>
	</div>
<% end %>
<h2 class="opening_quote">"Space is the breath of art"</h2>
<h5 class="text">-Frank Lloyd Wright</h5>

<div id="focal">
</div>